<a href="https://colab.research.google.com/github/ASO1801021/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### sklearnでエラーが出るので、前のバージョンを入れ直す

In [1]:
# 現在のscikitーlearnをcolabのVMからアンインストール
!pip uninstall scikit-learn
# 前のバージョンを指定してvmにインストール
!pip install scikit-learn==0.20 --ignore-installed

Uninstalling scikit-learn-0.22.2.post1:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/scikit_learn-0.22.2.post1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-0.22.2.post1
     |████████████████████████████████| 5.3MB 3.6MB/s 
     |████████████████████████████████| 14.5MB 307kB/s 
     |████████████████████████████████| 25.9MB 170kB/s 
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.4 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement scipy==1.4.1, but you'll have scipy 1.5.4 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.


### all_estimators()でループして各種のアルゴリズムで学習させ、比較する

In [2]:
# ライブラリ読み込み
import pandas as pd
# 学習用データとテスト検証用データを分割する
from sklearn.model_selection import train_test_split
# 正解率を算出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimaios(推定機の全てを利用できるようにする)
from sklearn.utils.testing import all_estimators
# 警告クラス
import warnings

### Webからあやめのデータを読み込む

In [3]:
# urリンクから読み込むライブラリ
import urllib.request as req
# url用の文字列変数を定義
url ="https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
#リンクから保存するためのファイル名を定義
savefile = "iris.csv"
# requestクラスを使ってurlからデータをsavefileへコピーして保存
req.urlretrieve(url,savefile)
#pandasのreadメソッドを使ってcsvファイルを読み込む
iris_data = pd.read_csv(savefile,encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

### アヤメデータを目的変数yと説明変数xに分離する

In [4]:
y = iris_data.loc[:, "Name"] #目的変数
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]] #説明変数

print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


### アヤメデータをさらに学習用とテストように分離する

In [5]:
# 学習用データ（train）と検証用データ（test）に分離
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,train_size=0.8,shuffle=True)
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
30           4.8         3.1          1.6         0.2
18           5.7         3.8          1.7         0.3
54           6.5         2.8          4.6         1.5
56           6.3         3.3          4.7         1.6
141          6.9         3.1          5.1         2.3
30         Iris-setosa
18         Iris-setosa
54     Iris-versicolor
56     Iris-versicolor
141     Iris-virginica
Name: Name, dtype: object
     SepalLength  SepalWidth  PetalLength  PetalWidth
101          5.8         2.7          5.1         1.9
127          6.1         3.0          4.9         1.8
43           5.0         3.5          1.6         0.6
144          6.7         3.3          5.7         2.5
88           5.6         3.0          4.1         1.3
101     Iris-virginica
127     Iris-virginica
43         Iris-setosa
144     Iris-virginica
88     Iris-versicolor
Name: Name, dtype: object


### allAlgorithmsにclassifierを指定して「分類」でフィルターしたアルゴリズムの推定器群を取得する

In [6]:
# 推定器のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
# ワーニングを無視する
warnings.filterwarnings("ignore")

### 推定器のリストをループしながら学習&推論させる

In [7]:
#推定器のリストをループ
for(name,algorithm) in allAlgorithms:
  #各アルゴリズムのオブジェクトを生成
  clf = algorithm() # 各アルゴリズムクラスのコンストラクトを実行
  #　学習させる
  clf.fit(x_train,y_train)
  # 推論する
  y_pred = clf.predict(x_test)
  # accuracy_scoreで正解率を算出して表示
  print(name,"正解率 = ",accuracy_score(y_test,y_pred) )

AdaBoostClassifier 正解率 =  0.9666666666666667
BaggingClassifier 正解率 =  0.9666666666666667
BernoulliNB 正解率 =  0.26666666666666666
CalibratedClassifierCV 正解率 =  0.9333333333333333
ComplementNB 正解率 =  0.5666666666666667
DecisionTreeClassifier 正解率 =  0.9666666666666667
ExtraTreeClassifier 正解率 =  0.9666666666666667
ExtraTreesClassifier 正解率 =  0.9666666666666667
GaussianNB 正解率 =  0.9333333333333333
GaussianProcessClassifier 正解率 =  0.9666666666666667
GradientBoostingClassifier 正解率 =  0.9666666666666667
KNeighborsClassifier 正解率 =  1.0
LabelPropagation 正解率 =  0.9666666666666667
LabelSpreading 正解率 =  0.9666666666666667
LinearDiscriminantAnalysis 正解率 =  0.9666666666666667
LinearSVC 正解率 =  0.9666666666666667
LogisticRegression 正解率 =  0.9333333333333333
LogisticRegressionCV 正解率 =  0.9333333333333333
MLPClassifier 正解率 =  0.9666666666666667
MultinomialNB 正解率 =  0.8
NearestCentroid 正解率 =  0.8666666666666667
NuSVC 正解率 =  0.9666666666666667
PassiveAggressiveClassifier 正解率 =  0.7333333333333333
Perceptron

##クロスバリデーション

### クロスバリデーション 関連のライブラリのインポート

In [8]:
# ライブラリのインポート
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

### クロスバリデーション を実行する

In [9]:
# K分割交差検証用のインスタンスを生成する
Kfold = KFold(n_splits=5,shuffle=True)
# 　すでに生成してあるall_astimatorsのインスタンスをループさせて、クロスバリデーション を行う
for(name,algorithm) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    #scoreの属性がある学習モデルだけに送る
    if hasattr(clf,"score"):
      scores = cross_val_score(clf,x,y,cv=kfold_cv)
      #k=n splits=5回分のクロスバリデーション のスコアを表示
      print(name,"の正解率")
      print(scores)
      #ifブロック終了
    #tryブロック終了
  except: #例外処理のブロック
    #何もしない
    pass

### おまけ:cross_val_scoreもっと詳しい結果を取得できる新しいクロスバリデーションオブジェクト:cross_validate

In [10]:
# ライブラリのインポート
from sklearn.model_selection import cross_validate

### cross_validateを使ったクロスバリデーション

In [11]:
# K分割考査検証
kfold_cv = KFold(n_splits=5, shuffle=True)
# すでに生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for( name, algorithms ) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    # scoreの属性がある学習モデルだけに絞る
    if hasattr( clf, "score" ):
      # クロスバリデーションをしてスコアを取得する
      scores = cross_validate(clf,x,y, cv=kfold_cv)
      #　k=n_splits=5 回文のクロスバリデーションのスコアを表示
      print( name, "の正解率" )
      print( scores )
    # ifブロックの終了
  # tryブロックの終了
  except: # 例外処理ブロック
    # 何もしない
    pass

AdaBoostClassifier の正解率
{'fit_time': array([0.00374675, 0.00297308, 0.00327492, 0.00311613, 0.00180674]), 'score_time': array([0.00131083, 0.0015893 , 0.00137186, 0.0012114 , 0.00077295]), 'test_score': array([0.93333333, 0.96666667, 0.96666667, 1.        , 1.        ]), 'train_score': array([0.98333333, 0.99166667, 0.98333333, 0.98333333, 0.99166667])}
BaggingClassifier の正解率
{'fit_time': array([0.00180221, 0.00167227, 0.00165701, 0.00171304, 0.00175977]), 'score_time': array([0.00076342, 0.00073433, 0.00074792, 0.00076127, 0.00072718]), 'test_score': array([1.        , 0.96666667, 1.        , 1.        , 0.96666667]), 'train_score': array([0.975     , 0.99166667, 0.99166667, 0.98333333, 0.98333333])}
BernoulliNB の正解率
{'fit_time': array([0.00288534, 0.00176716, 0.00185251, 0.00197911, 0.00172091]), 'score_time': array([0.00087261, 0.00076461, 0.00077939, 0.0007925 , 0.00077438]), 'test_score': array([0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ]), 'train_score': array([0.

### Numpyの動作確認

In [12]:
# import
import numpy as np

In [13]:
# numpy配列の初期化
a = np.array([1,2,3,4,5]) # numpy配列オブジェクトを生成
print(a)
# 型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<class 'numpy.ndarray'>

In [14]:
# 二次元のndarrayを定義
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
# 配列の要素数を指定して０うめで初期化
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [16]:
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(5,8,0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [17]:
# numpyで行列計算
a = np.array([1,2,3,4,5])
b = a*2
print(b)
x = np.arange(10)
print(x)
y = 3*x + 5
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [20]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [21]:
# Numpy配列で次元数を変換する
a = np.array([[1,2,3],[4,5,6]])
print("a=", a)
b = a.flatten()
print("b=", b)

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape(3,2)
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### numpyの配列にアクセスする方法

In [22]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]
print(a) # 二次元配列の０行目
b = v[1:] #  一列目いこう
print(b)
c = v[:,0]
print(c)

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
